sudo: false

language: node_js
node_js:
  - "10.13.0"

os: osx  
osx_image: xcode10.1
addons:
  chrome: beta

branches:
  only:
  - master
  - develop

install:
  - npm install -g ionic
  - npm i -g cordova@6.5.0
  - npm install --unsafe-perm=true

before_install:
  - "/Applications/Google\\ Chrome.app/Contents/MacOS/Google\\ Chrome --headless --crash-dumps-dir=/tmp --disable-gpu --remote-debugging-port=9222 http://localhost &"

before_script:
  - npm install -g @angular/cli@1.7.4
  - gem install cocoapods

script:
  - ionic cordova platform add ios
  - cd platforms/ios
  - pod init
  - pod install
  - cd ../..
  - ionic cordova build ios
  - npm test

deploy:
 provider: pages
 skip-cleanup: true
 github-token: $GITHUB_TOKEN 
 keep-history: true
 on:
   branch: master
 local_dir: www