sudo: false

language: node_js
node_js:
  - "10.13.0"

os: osx  
osx_image: xcode10.1

branches:
  only:
  - master
  - develop

install:
  - npm install -g cordova ionic
  - npm install

before_install:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

before_script:
  - npm install -g @angular/cli

script:
  - ionic cordova build ios --no-build
  - npm test

deploy:
 provider: pages
 skip-cleanup: true
 github-token: $GITHUB_TOKEN 
 keep-history: true
 on:
   branch: master
 local_dir: www