sudo: false

language: node_js
node_js:
  - "10.13.0"

branches:
  only:
  - master
  - develop

install:
  - npm install -g cordova ionic
  - npm install

before_script:
  - npm install -g @angular/cli

script:
  - ionic cordova build ios
  - npm test --watch=false

deploy:
 provider: pages
 skip-cleanup: true
 github-token: $GITHUB_TOKEN 
 keep-history: true
 on:
   branch: master
 local_dir: www